[2025-08-06 14:18:13,896] — 27 —INFO — root — Logging has started
[2025-08-06 14:18:26,791] — 30 —ERROR — root — Exception occurred
Traceback (most recent call last):
  File "C:\Users\DELL\Downloads\Savleen_LearnCode\ML-Project\src\exception.py", line 28, in <module>
    a=1/0
ZeroDivisionError: division by zero
[2025-08-06 14:19:50,181] - 30 - ERROR - root - Exception occurred
Traceback (most recent call last):
  File "C:\Users\DELL\Downloads\Savleen_LearnCode\ML-Project\src\exception.py", line 28, in <module>
    a=1/0
ZeroDivisionError: division by zero
